Successfully compose Fast-JX and SuperFast
EarthSciML/GasChem.jl pull request #21
Opened 2023-01-20 16:24 UTC by jialinl6

To update the codes of composing Fast-JX and SuperFast. I will update the documentation tomorrow.

2023-01-24 21:00 UTC, ctessum requested changes
Thanks, this looks good!

I've made some comments below (or above?)

One additional thing is to run the formatter on each of the files: https://www.julia-vscode.org/docs/stable/userguide/formatter/

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Building_model.jl
> +  # Converting the ReactionSystem to an ODESystem adds extra terms for the
Move this documentation to be a text string above the function declaration, i.e.

``` julia
""""
Converting the ReactionSystem to an ODESystem adds extra terms for the
derivatives of the photolysis rate constants. We need to remove these terms before
adding the fast-jx equations.
"""
function remove_D(superfast)
```

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Building_model.jl
> +using ModelingToolkit
These first four lines should all go in `src/GasChem.jl`

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Building_model.jl
> +          @info term, eq.lhs, isequal(term, eq.lhs)
We should remove these @info statements before checking the code into github.

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Building_model.jl
> +  @named superfast = ODESystem(sf_eqs, t, states(sf), parameters(sf))
change to 

``` julia
ODESystem(sf_eqs, t, states(sf), parameters(sf); nameof(superfast))
```

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Building_model.jl
> +using ModelingToolkit
Move this file to the main `src` directory, not in the `composing_models` subfolder. Also, since there may be more than one model we want to build, we should give this file a more descriptive name, such as `fastjx_connections.jl`.

Then, we should add a line in `src/GasChem.jl` to include this file in the overall package, i.e. `include("fastjx_connections.jl")`

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Building_model.jl
> +@parameters t
Change this code to a function (e.g. named `compose_fastjx_superfast`) that takes fastjx and superfast models as arguments and then returns the coupled model.

So something like:

``` julia
       compose_fastjx_superfast(fastjx, superfast)

Compose superfast and fast-jx models together.

# Example:
''' julia
using GasChem, ModelingToolkit, DifferentialEquations, Plots

@parameters t
sf = superfast(t)
fj = fast_jx(t)
connected = compose_fastjx_superfast(fastjx, superfast)
tspan = (0.0, 3600*24*2)
sol = solve(ODEProblem(simplified_sys, [], tspan, [], 
       combinatoric_ratelaws=false),Tsit5(), saveat=10.0)

plot(sol,ylims=(0,20),xlabel="Time (second)", ylabel="concentration (ppb)",legend=:outertopright)
'''
function compose_fastjx_superfast(fastjx, superfast)
       r_sf = remove_D(superfast)
     @named fastjx_superfast = ODESystem([
               r_sf.jH2O2 ~ fj.j_h2o2
                r_sf.jCH2Oa ~ fj.j_CH2Oa
               r_sf.jCH3OOH ~ fj.j_CH3OOH
               r_sf.jNO2 ~ fj.j_NO2
               r_sf.jO31D ~ fj.j_o31D
         ], t, systems=[r_sf, fj])
end
```

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +using ModelingToolkit
Instead of creating a new version of this file, instead just make these changes directly in `src/Fast-JX.jl`.

Then, delete the `using` statements here but make sure they're all in `src/GasChem.jl` (if needed).

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +using ModelingToolkit
Also, add `export fast_jx` at the top of this file (or the equivalent one in the `src` directory so the `fast_jx` function will be available to users of the library.

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +#   Description: This is a box model used to calculate the photolysis reaction rate constant using the Fast-JX scheme (Neu, J. L., Prather, M. J., and Penner, J. E. (2007), Global atmospheric chemist
Move this documentation to be a documentation string for the `fast_jx` function below.

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +#   Basic Input infromation:
infromation -> information

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +    # 18 wavelength bins covering 177–850 nm
If this comment applies to the line of code above, move it up and  merge it with line 11

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +    # first column: 200K
Move this documentation closer to the code it describes, e.g.:

``` julia
[
      [4.842, 4.922, 5.071, 5.228, 6.040, 6.803, 7.190, 7.549, 9.000, 8.989, 8.929, 9.000, 8.901, 4.130, 8.985*0.1, 6.782*0.1, 0.000, 0.000]*0.1; # first column: 200K
      [4.843, 4.922, 5.072, 5.229, 6.040, 6.802, 7.189, 7.549, 9.000, 8.989, 8.929, 9.000, 8.916, 4.656, 1.417, 6.995*0.1, 0.000, 0.000]*0.1; # second column: 260K
     [4.843, 4.922, 5.072, 5.229, 6.040, 6.805, 7.189, 7.550, 9.000, 8.989, 8.929, 9.000, 8.967, 5.852, 2.919, 7.943, 0.000, 0.000]*0.1 # third column: 320K
]
```
And do the same thing for the other tables below.

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +        #j_CH2Ob ~ mean_J_CH2Ob(t,lat,T)*j_unit
If we don't need this line of code, just delete it. If it's something that we need to return to and fix later, document it like:

``` julia
# TODO(JL): Fix this by...
```

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +    # fj = fast_jx(t)
Add this code as a documentation example for the `fast_jx` function as demonstrated in the comment above for a different function.

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +    # fj = fast_jx(t)
In general, we want to delete any code we're not using rather than just commenting it out. Have a bunch of commented-out code just hanging around makes it difficult for readers to understand what's going on, as you have probably seen in GEOS-Chem

2023-01-24 21:00 UTC, ctessum commented on src/composing_models/SuperFast.jl
> +using Catalyst
As above, just make changes to `src/SuperFast.jl` rather than making a whole new file.

2023-01-24 21:00 UTC, ctessum commented on docs/src/composing_models.md
> +function remove_D(superfast)
Once you create a function like `compose_fastjx_superfast` as described below, you can use that function in the documentation here.

2023-01-24 21:05 UTC, ctessum commented on src/composing_models/Building_model.jl
> +  @named superfast = ODESystem(sf_eqs, t, states(sf), parameters(sf))
actually:

``` julia
ODESystem(sf_eqs, t, states(sf), parameters(sf); name=nameof(superfast))
```

2023-01-24 21:09 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +        # @parameters σ_ = IfElse.ifelse(T <= 200, table_σ_H2O2_jx[:,1], table_σ_H2O2_jx[:,2])
As elsewhere, delete commented-out code

2023-01-25 15:58 UTC, jialinl6 commented on src/composing_models/Fast-JX.jl
> +    # first column: 200K
After I used JuliaFormatter, it looks like this, is it okay?
`
[
     # 200K
     [.
      .
      .],
     # 260K
     [.
      .
      .],
     # 320K
     [.
      .
      .]
]
`

2023-01-25 17:14 UTC, ctessum commented on src/composing_models/Fast-JX.jl
> +    # first column: 200K
Maybe just manually change that back so it's not taking up so many lines. The formatter doesn't always do the right thing.

2023-01-26 05:29 UTC, jialinl6 commented on src/composing_models/Fast-JX.jl
> +    # first column: 200K
Sure!

2023-01-26 16:46 UTC, ctessum approved these changes
Looks good, thanks!

2023-01-26 16:46 UTC, merged