Update to MTKv9
EarthSciML/GasChem.jl pull request #92
Opened 2024-08-27 05:22 UTC by jialinl6

2024-08-27 13:38 UTC, ctessum requested changes
Thanks!

2024-08-27 13:38 UTC, ctessum commented on Project.toml
> +SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
I think this line might not be necessary but I'm not sure.

2024-08-27 13:38 UTC, ctessum commented on src/GasChem.jl
> +@register_unit ppb 1
I think this only works because `ppb` is unitless here, so `1ppb == 1`,  whereas for example `1u"s" != 1`. So when we use the ppb unit in ModelingToolkit, it is actually treated as a number without any units at all, which is not what we want.

However, with this change: https://github.com/SciML/ModelingToolkit.jl/pull/2621 , we should be able to use "symbolic units", e.g.:

```julia
@variables x(t) = 1.0 [unit=us"nmol/mol"]
```

I believe this will allow us to use non-SI units, even if it's not something like ppb which is actually unitless. Some documentation is here: https://symbolicml.org/DynamicQuantities.jl/dev/symbolic_units/

2024-08-27 18:34 UTC, jialinl6 commented on Project.toml
> +SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
You're right. This package was unnecessary. I've removed it.

2024-09-04 20:07 UTC, ctessum approved these changes
Thanks!

2024-09-04 20:07 UTC, merged